<a href="https://colab.research.google.com/github/VivekRupapara146/Royal-Internship/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Time-Line
* Numpy
* pandas
* matpolt
* Web Scrapting
* OpenCV
* skLearn with algo
* tensorFlow
* basic fLaskAPI


# Array

In [ ]:
import numpy as np
import random as r

In [ ]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [ ]:
#2 D array
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
# np.zeros() , np.ones() --- float values
z1 = 7*np.ones((3,3))
print(z1)
print(z1.dtype)
#z2 = np.full((Size), value)
z2 = np.full((3,3), 7)
print(z2)
print(z2.dtype)


[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
float64
[[7 7 7]
 [7 7 7]
 [7 7 7]]
int64


In [ ]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# y = np.array([[1,2,3],[4,5,6]])
y = np.array([1,2,3,4,5,6])
print(y)
print(y.shape)
print(y.size)
print(y.ndim)
print(y.dtype)

[1 2 3 4 5 6]
(6,)
6
1
int64


In [ ]:
x1 = np.empty(10)
print(x1)

[4.70452272e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.17425884e+165 1.16188862e+165 5.45311699e-090
 7.24924433e+169 8.48797786e-315]


# Maths Opperation
* *+*
* *-*
* *
* */*

* .sum()

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)
print((x+y).dtype)
print(x-y)
print(x*y)
print((x*y).dtype)
print(x/y)  # float division

[5 7 9]
int64
[-3 -3 -3]
[ 4 10 18]
int64
[0.25 0.4  0.5 ]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])
print(x+y)
print((x+y).dtype)
print(x-y)
print(x*y)
print((x*y).dtype)
print(x/y)  # float dividion

[[ 2  4  6]
 [ 8 10 12]]
int64
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
int64
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
x = np.arange(1,11)
# x = [1,2,3,4,5,6,7]
print(x)
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())
print(x.std())

[ 1  2  3  4  5  6  7  8  9 10]
55
1
10
5.5
2.8722813232690143


In [ ]:
x = np.arange(1,11)
y = np.arange(11,21)
ans = np.sum(x)
print(ans)
ans = np.sum(x+y) # same dimensions inside
print(ans)

55
210


In [ ]:
#2D array

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print()
print(y)
print()
ans = np.sum(x, axis=0) # column wise
print(ans)
ans = np.sum(x, axis=1) # row wise
print(ans)
print('max,min,mean,sum')
print(np.max(x))
print(np.min(x))
print()
print('mean,median')
print(np.mean(x))
print(np.median(x))
print(np.sum(x))
print(np.sum(x,axis=0))
# print(x.sum(axis=0))
print(np.sum(x,axis = 1))
print(np.sum(x+y,axis=0))
print(np.sum(x+y,axis=1))



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[12 15 18]
[ 6 15 24]
max,min,mean,sum
9
1

mean,median
5.0
5.0
45
[12 15 18]
[ 6 15 24]
[24 30 36]
[12 30 48]


In [ ]:
x = np.array([10,11,23,45,76,123,67,90])
ans = np.mean(x)
print(ans)

55.625


In [ ]:
x = np.array([10,11,23,45,76,123,67,90])
ans = np.median(x)
print(ans)

56.0


median = [(n/2)th element + (n/2)+1 th element] / 2

In [ ]:
x = np.array([10,11,23,45,76,123,67,90])
ans1 = np.max(x)
ans2 = np.min(x)
print(ans1)
print(ans2)
# print(ans3)

123
10


In [ ]:
x = np.arange(1,10)
print(x)
print(x.ndim)
y = x.reshape(3,3)
print(y)
print(y.ndim)


[1 2 3 4 5 6 7 8 9]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


# Multi-Dimentional

In [ ]:
y = np.array([1,2,3,4])
print(y.ndim)
print(y)
print(y.shape)
print()
y = np.array([[1,2,3],[4,5,6],[5,6,7]])
print(y.ndim)
print(y)
print(y.shape)
print()
y = np.array([[[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]]])
print(y.ndim)
print(y)
print(y.shape)


1
[1 2 3 4]
(4,)

2
[[1 2 3]
 [4 5 6]
 [5 6 7]]
(3, 3)

3
[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]]
(3, 3, 3)


In [ ]:
print('maths opps')
x = np.array([[[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]]])

y = np.array([[[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]],
              [[1,2,3],[4,5,6],[5,6,7]]])

print('add')
print(x+y)
print('sub')
print(x-y)
print('mul')
print(x*y)
print('div')
print(x/y)
print()



maths opps
add
[[[ 2  4  6]
  [ 8 10 12]
  [10 12 14]]

 [[ 2  4  6]
  [ 8 10 12]
  [10 12 14]]

 [[ 2  4  6]
  [ 8 10 12]
  [10 12 14]]]
sub
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
mul
[[[ 1  4  9]
  [16 25 36]
  [25 36 49]]

 [[ 1  4  9]
  [16 25 36]
  [25 36 49]]

 [[ 1  4  9]
  [16 25 36]
  [25 36 49]]]
div
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]



In [ ]:
print(x)
print(x.shape)
print('.sum()')
print(np.sum(x))
print('--axis(0)')
print(np.sum(x,axis=0))
print('--axis(1)')
print(np.sum(x,axis=1))
print('--axis(2)')
print(np.sum(x,axis=2))
print()

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]]
(3, 3, 3)
.sum()
117
--axis(0)
[[ 3  6  9]
 [12 15 18]
 [15 18 21]]
--axis(1)
[[10 13 16]
 [10 13 16]
 [10 13 16]]
--axis(2)
[[ 6 15 18]
 [ 6 15 18]
 [ 6 15 18]]



In [ ]:
print('.mean()')
print(np.mean(x))
print('.mean(axis=0)')
print(np.mean(x,axis=0))
print('.mean(axis = 1)')
print(np.mean(x,axis=1))
print('.mean(axis = 2)')
print(np.mean(x,axis=2))

.mean()
4.333333333333333
.mean(axis=0)
[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 7.]]
.mean(axis = 1)
[[3.33333333 4.33333333 5.33333333]
 [3.33333333 4.33333333 5.33333333]
 [3.33333333 4.33333333 5.33333333]]
.mean(axis = 2)
[[2. 5. 6.]
 [2. 5. 6.]
 [2. 5. 6.]]


In [ ]:
print('.max()')
print(np.max(x))
print('.max(axis = 0)')
print(np.max(x,axis=0))
print('.max(axis = 1)')
print(np.max(x,axis=1))
print('.max(axis =2)')
print(np.max(x,axis=2))

.max()
7
.max(axis = 0)
[[1 2 3]
 [4 5 6]
 [5 6 7]]
.max(axis = 1)
[[5 6 7]
 [5 6 7]
 [5 6 7]]
.max(axis =2)
[[3 6 7]
 [3 6 7]
 [3 6 7]]


In [ ]:
print('.min()')
print(np.min(x))
print('.min(axis = 0)')
print(np.min(x,axis=0))
print('.min(axis = 1)')
print(np.min(x,axis=1))
print('.min(axis = 2)')
print(np.min(x,axis=2))

.min()
1
.min(axis = 0)
[[1 2 3]
 [4 5 6]
 [5 6 7]]
.min(axis = 1)
[[1 2 3]
 [1 2 3]
 [1 2 3]]
.min(axis = 2)
[[1 4 5]
 [1 4 5]
 [1 4 5]]


In [ ]:
# x.median() --- object calling method median --- no method exist
# in py np mean sum min max also exist as method for object ndarray
# np.median(x) --- function in np called and given argument x
print(x)
print()
print(np.median(x))
print()
print(np.median(x,axis=0))
print()
print(np.median(x,axis=1))
print()
print(np.median(x,axis=2))
print()

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 2 3]
  [4 5 6]
  [5 6 7]]]

5.0

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 7.]]

[[4. 5. 6.]
 [4. 5. 6.]
 [4. 5. 6.]]

[[2. 5. 6.]
 [2. 5. 6.]
 [2. 5. 6.]]



# Slicing

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# 1 2 3 4 5 6 6 7 8 9 10
# 0 1 2 3 4 5 6 7 8 9
# -10 -9 -8 -7 -6- -5 -4 -3 -2 -1
print(arr[1])
print(arr[1:5])
print(arr[:10])
print(arr[:1000])   # list and tuple slicing give error if index out of bonds but numpy ignores it
print(arr[0:])
print(arr[1::2])
print(arr[-1])
print(arr[-10:-1])
print(arr[-10:-1:2])

2
[2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
10
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


#Reshaping

## 1-D to Multi

In [ ]:
# np.reshape(array, new_shape)
# array.reshape(new_shape)

# new_shape must be same size as original


24 =
1,12,2
1,6,4
1,8,3
2,2,6
2,3,4
.reshape(rows,-1) -- automatically decides columns and vice-versa


In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
print()
a1 = a.reshape(2,3)
print(a1)
print(a1.shape)
print()
a2 = a.reshape(3,2)
print(a2)
print(a2.shape)
print()

[1 2 3 4 5 6]
(6,)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)



In [ ]:
x = np.arange(12)
print(x)
print()
x1 = x.reshape(3,4)
print(x1)
print()
x2 = x.reshape(4,-1)  # 12 = 1,2,3,4,6,8,12
print(x2)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



In [ ]:
x = np.arange(24)
print(x)
print()
x1 = x.reshape(2,3,4)
print(x1)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



## Multi to 1-D

In [ ]:
# flatten()

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print()
a1 = a.flatten()
print(a1)
print(a1.shape)
print()
a2 = a.flatten('F')
print(a2)
print(a2.shape)
print()
a3 = a.flatten('C')
print(a3)
print(a3.shape)
print()
a4 = a.flatten('K')
print(a4)
print(a4.shape)
print()
a5 = a.flatten('A')
print(a5)
print(a5.shape)
print()
x = np.arange(24).reshape(2,3,4)
print(x)
print()
x1 = x.flatten()
print(x1)
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[ 0  4  8  1  5  9  2  6 10  3  7 11]
(12,)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]



# .flatten()

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

a1 = a.flatten()
print(a1)
print(a1.shape)

x1 = np.arange(24).reshape(4,3,2)
print(x1)
print(x1.shape)

b2 = x1.flatten()
print(b2)
print(b2.shape)


x3 = np.arange(12).reshape(4,3)
print(x3)

#column

b3 =  x3.flatten(order="F")
print(b3)
print(b3.shape)



b4 = x3.flatten(order="C")
print(b4)
print(b4.shape)

#memory order
b4 = x3.flatten(order="K")
print(b4)
print(b4.shape)

b4 = x3.flatten(order="A")  # same as C , arrange as per original array stored in memory
print(b4)
print(b4.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


# .random()

Give 5 - real time examples for random array generation

In [ ]:
print(r.random()) # bet 0 - 1 ,1 excluded

0.5951151521984479


In [ ]:
print(r.randrange(1,10,2))  # start, end, skip, don't include 10

1


In [ ]:
print(r.randint(1,10))  # include 10

3


In [ ]:
a = np.random.randint(low= -10, high = 10, size = (2,5))  #.reshape(2,5)
print(a)

[[-2 -6  9 -3 -6]
 [ 1  7 -2  8  9]]


In [ ]:
x = np.random.rand(3,4)
print(x)

[[0.34332762 0.34924076 0.27767006 0.88311461]
 [0.30215499 0.94114061 0.61353409 0.73455761]
 [0.48961845 0.3624765  0.58875015 0.37145079]]


In [ ]:
print(r.seed())

None


In [ ]:
# argmax(axis) argmin(axis) sort(axis) argsort(axis)
# arg function returns the index of the array no data

# Something new


1. array printing:

    use np.ones()

        [[1 1 1 1 1],
         [1 0 0 0 1],
         [1 0 9 0 1],
         [1 0 0 0 1],
         [1 1 1 1 1]]

In [ ]:
x = np.ones((5,5), dtype = int)
print(f"{x}\n")
x[1:-1,1:-1] = 0
x[2:3,2:3] = 9
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


2. Array patterns

    make a 5x5 array
        
        [[ 1  2  3  4  5]
        [ 6  7  8  9 10]
        [11 12 13 14 15]
        [16 17 18 19 20]
        [21 22 23 24 25]]

    output:
        
        1) [[2,8,14,20]]
        2) [[4,5],
           [19 ,20],
           [24,25]]

In [ ]:
x = np.arange(1,26).reshape(5,5)
print(x)
print()
print(x[[0,1,2,3],[1,2,3,4]]) # specific rows and colums given as parameters
print()
print(x[[0,3,4],3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 2  8 14 20]

[[ 4  5]
 [19 20]
 [24 25]]


## Identity matrix

In [ ]:
a = np.eye(5, dtype = int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
