<a href="https://colab.research.google.com/github/VivekRupapara146/Royal-Internship/blob/Tasks/PyTasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [ ]:
import numpy as np
import random as rd

1. Array Creation
Create a NumPy array of numbers from 1 to 20. Then print its size.

In [ ]:
arr = np.arange(1,21)
print(arr)
print(arr.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


2. Zeros & Ones
Create:

* a 3×4 array filled with zeros

* a 2×5 array filled with ones

In [ ]:
a1 = np.zeros((3,4), dtype = int)
print(a1)
print()
a2 = np.ones((2,5), dtype=int)
print(a2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1 1 1 1 1]
 [1 1 1 1 1]]


3. Full Function
  - Create a 4×4 array where every value is 7 using NumPy.

In [ ]:
a3 = np.full((4,4), 7)
print(a3)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


4. Reshape
* Create an array from 1 to 12 and reshape it into:

    3×4

    2×6


In [ ]:
a4 = np.arange(1,13).reshape(3,4)
print(a4)
print()
a5 = np.arange(1,13).reshape(2,6)
print(a5)
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]



5. Flatten

    Take a 3×3 matrix and convert it into a 1D array using flatten.

In [ ]:
a6 = np.arange(9).reshape(3,3)
print(a6)
print()
a7 = a6.flatten()
print(a7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]


6. Arrange (arange)
    
    Create an array starting from 10 to 50 with a step of 5.

In [ ]:
a8 = np.arange(10, 51, 5)  #[10::5]
print(a8)

[10 15 20 25 30 35 40 45 50]


7. Sum of Elements
    
    Given array:
    
        [10, 20, 30, 40, 50]
    
    Find:
        
        total sum

        sum of first 3 elements only

In [ ]:
a9 = np.array([10,20,30,40,50])
# a9 = np.arange(10,51,10)
print(a9)
print()
sumTotal = np.sum(a9)
sumOf3 = np.sum(a9[:3])
print(sumTotal)
print()
print(sumOf3)

[10 20 30 40 50]

150

60


8. Matrix Addition

    Add the following two arrays:

        A = [[1,2,3],
            [4,5,6]]
            
        B = [[6,5,4],
            [3,2,1]]


In [ ]:
A = np.arange(1,7).reshape(2,3)
# print(A)
B = np.arange(6,0,-1).reshape(2,3)
# print(B)
# print(A+B)
sum = np.add(A,B)
print(sum)

[[7 7 7]
 [7 7 7]]


9. Matrix Subtraction
  
    Subtract array B from array A (from Q8).

In [ ]:
dif = np.subtract(A,B)
print(dif)
# print(A-B)

[[-5 -3 -1]
 [ 1  3  5]]


10. Element-wise Multiplication
    
    Multiply arrays A and B element by element.

In [ ]:
mult = np.multiply(A,B)
print(mult)
# print(A*B)

[[ 6 10 12]
 [12 10  6]]


11. Mean
    
    Find the mean of:
      
        [12, 15, 20, 25, 30]

In [ ]:
x = np.array([12,15,20,25,30])
mean = np.mean(x)
print(mean)

20.4


12. Median
    
    Find the median of:
      
        [5, 2, 9, 1, 7, 6]

In [ ]:
x1 = np.array([5,2,9,1,7,6])
median = np.median(x1)
print(median)

5.5


13. Standard Deviation
      
      Find the standard deviation of:
          
        [4, 8, 6, 5, 3, 7]


In [ ]:
x2 = np.array([4,8,6,5,3,7])
std = np.std(x2)
print(x2)

[4 8 6 5 3 7]


14. & 15. Sum

    Given matrix:

        [[1,2,3],
        [4,5,6],
        [7,8,9]]

    Find sum of each row and col separately.

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)
rowSum = np.sum(arr1)
print(rowSum)
rowWiseSum = np.sum(arr1,axis=1)
print(rowWiseSum)
colWiseSum = np.sum(arr1, axis = 0)
print(colWiseSum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]
[12 15 18]


16. Reshape + Mean
    
    Create numbers from 1 to 16, reshape into 4×4, then find the mean of each row.


In [ ]:
x = np.arange(1,17).reshape(4,4)
print(x)
rowMean = np.mean(x,axis = 1)
print(rowMean)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2.5  6.5 10.5 14.5]


17. Flatten + Size

    Create a 5×5 ones matrix. Flatten it and find its size.

In [ ]:
x = np.arange(1,26).reshape(5,5)
print(x.shape)
print(x.size)

(5, 5)
25


18. Arithmetic Combination
    
    Given:

          A = [1,2,3,4]
          B = [5,6,7,8]

    Compute:
    
        (A + B) * 2

In [ ]:
x = np.arange(1,5)
y = np.arange(5,9)
ans = (x+y)*2
print(ans)

[12 16 20 24]


19. Mixed Operations

    Create array from 1–9, reshape to 3×3. Multiply entire matrix by 5 and then find total sum.

In [ ]:
x = np.arange(1,10).reshape(3,3)*5
print(x)
print(np.sum(x))

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
225


20. Statistics Combo
    
    Given:
    
        [15, 18, 21, 24, 27, 30]

    Find:

        mean

        median

        standard deviation

In [ ]:
arr = np.array([15,18,21,24,27,30])
print(f'mean = {np.mean(arr)}')
print(f'median = {np.median(arr)}')
print(f'std = {np.std(arr)}')

mean = 22.5
median = 22.5
std = 5.123475382979799


## Hard

1. Advanced Reshape + Sum

    Create an array from 1 to 48. Reshape it into 4 × 4 × 3.
    
    Find:

        sum along axis 0
        sum along axis 1
        sum along axis 2

In [ ]:
x = np.arange(1,49).reshape(4,4,3)
print(x)
print()
sum1 = np.sum(x,axis = 0) # index wise
sum2 = np.sum(x,axis = 1) # column wise
sum3 = np.sum(x,axis =2) # row wise
print(sum1)
print()
print(sum2)
print()
print(sum3)
print()

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

[[ 76  80  84]
 [ 88  92  96]
 [100 104 108]
 [112 116 120]]

[[ 22  26  30]
 [ 70  74  78]
 [118 122 126]
 [166 170 174]]

[[  6  15  24  33]
 [ 42  51  60  69]
 [ 78  87  96 105]
 [114 123 132 141]]



2. Conditional Replacement

    Create array from 1 to 20.
    Replace all numbers:

        divisible by 3 → -1

        divisible by 5 → 100

    (Do it using NumPy, not loops.)

In [ ]:
x = np.arange(1,21)
print(x)
print()
# x = np.where(x%3 == 0, -1,x)
# x = np.where(x%5 == 0, 100,x)
x[x%3==0] = -1
x[x%5==0] = 100
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[  1   2  -1   4 100  -1   7   8  -1 100  11  -1  13  14  -1  16  17  -1
  19 100]


3. Broadcasting Math

    Given:

        A = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])


        B = np.array([10,20,30])

    Add B to every row of A using broadcasting.

In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.array([10,20,30])

c = a+b
print(c)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


4. Flatten vs Ravel Logic

    Create a 3×3 matrix.
    Use ravel() to flatten and modify the first element.
    Then check whether original array changes.
    Explain why.

5. Indexing Challenge

    Create array 1–25 and reshape to 5×5.
    Extract:

        middle row

        last column

        corner elements only

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a)
"""
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 """
print()
print(a[2])
print()
print(a[0:5,4:])
print()
print(a[0:5:4,0:5:4])
# print(a[[0],[0]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[11 12 13 14 15]

[[ 5]
 [10]
 [15]
 [20]
 [25]]

[[ 1  5]
 [21 25]]


6. Statistical Axis Problem

    Given:

        arr = np.array([[10,20,30],
                      [40,50,60],
                      [70,80,90]])

    Find:

        mean of each column

        standard deviation of each row

In [ ]:
x = np.arange(10,91,10).reshape(3,3)
print(x)
print()
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))
print()
print(np.std(x,axis=0))
print(np.std(x,axis=1))

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[40. 50. 60.]
[20. 50. 80.]

[24.49489743 24.49489743 24.49489743]
[8.16496581 8.16496581 8.16496581]


7. Matrix Arithmetic Combo

    Create two random 3×3 arrays.
    
    Compute:

        (A + B) * 2 - A


In [ ]:
a = np.random.randint(1,10,(3,3))  #.reshape(3,3)
b = np.random.randint(1,10,(3,3)) #.reshape(3,3)
print(a)
print()
print(b)
print()
c = (a+b)*2-a
print(c)

[[2 5 5]
 [6 8 4]
 [9 5 8]]

[[5 3 3]
 [3 8 1]
 [6 1 2]]

[[12 11 11]
 [12 24  6]
 [21  7 12]]


8. Pattern Matrix

    Create this matrix using NumPy only:

        [[1,0,1,0],
        [0,1,0,1],
        [1,0,1,0],
        [0,1,0,1]]

    (No manual typing.)
    2 ways
    - using .indices()
    - using tile()

In [ ]:
x = np.indices((4,4))
print(x)
x = np.sum(x,axis=0)
print()
print(x)
print()
x = x%2
print(x)
print()
x = 1-x
print(x)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


9. 3D Array Stats

    Create array from 1–27 and reshape to 3×3×3.
    Find:

        overall mean

        mean along axis 0

        median of entire array

In [ ]:
x = np.arange(1,28).reshape(3,3,3)
print(f"{x}\n")
print(f"{np.mean(x)}\n")
print(f"{np.mean(x, axis = 0)}\n")
print(f"{np.median(x)}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

14.0

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]

14.0


10. Multi-step Transformation

    Create array from 1–16.
    Steps:

        Reshape to 4×4

        Multiply each column by [1,2,3,4]

        Flatten result

        Find standard deviation

In [ ]:
x = np.arange(1,17)
print(f"{x}\n")
y = x.reshape(4,4)
print(f"{y}\n")
z = y*np.arange(1,5)
print(f"{z}\n")
Zstd = np.std(z)
print(f"{Zstd}\n")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]

17.38533865071371



# Tasks in calss


1. array printing:

    use np.ones()

        [[1 1 1 1 1],
         [1 0 0 0 1],
         [1 0 9 0 1],
         [1 0 0 0 1],
         [1 1 1 1 1]]

In [ ]:
x = np.ones((5,5), dtype = int)
print(f"{x}\n")
x[1:-1,1:-1] = 0
x[2:3,2:3] = 9
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


2. Array patterns

    make a 5x5 array
        
        [[ 1  2  3  4  5]
        [ 6  7  8  9 10]
        [11 12 13 14 15]
        [16 17 18 19 20]
        [21 22 23 24 25]]

    output:
        
        1) [[2,8,14,20]]
        2) [[4,5],
           [19 ,20],
           [24,25]]

In [ ]:
x = np.arange(1,26).reshape(5,5)
print(x)
print()
print(x[[0,1,2,3],[1,2,3,4]]) # specific rows and colums given as parameters
print()
print(x[[0,3,4],3:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 2  8 14 20]

[[ 4  5]
 [19 20]
 [24 25]]


#Pandas

##Series Data Task

In [ ]:
import pandas as pd

1. Create a Series from [10, 20, 30, 40].

In [ ]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


2. Create a Series with values [5, 6, 7] and index ["a","b","c"].

In [ ]:
s= pd.Series([5,6,7], index = ['a','b','c'])
print(s)

a    5
b    6
c    7
dtype: int64


 3. Create a Series from dictionary:

```
{"Math": 85,
 "Sci": 90,
 "Eng": 88}
```

In [ ]:
dict1 = {
  'Math': 85,
  'Sci' : 90,
  'Eng': 88
  }
s = pd.Series(dict1)
print(s)

Math    85
Sci     90
Eng     88
dtype: int64


4. Create a Series with scalar value 100 repeated for 5 indices.

In [ ]:
s = pd.Series(np.full(5,100))
print(s)

0    100
1    100
2    100
3    100
4    100
dtype: int64


5. Print first 3 values of a Series.

In [ ]:
s1 = pd.Series(np.arange(10,101,10))
print(s1)
print(s1.head(3))

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64
0    10
1    20
2    30
dtype: int64


6.  Print last 2 values.

In [ ]:
print(s1.tail(3))

7     80
8     90
9    100
dtype: int64


7. Get the datatype of a Series.

In [ ]:
print(s1.dtype)

int64


8. Find number of elements in Series.

In [ ]:
print(s1.size)

10


9. Select value using label "b".

In [ ]:
s = pd.Series([10,20,30,40,50,60,70], index = ['a','b','c','d','e','f','g'])
print(f"s:\n{s}")
print()
print(s.loc['b'])

s:
a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

20


10. Select value using position 2.

In [ ]:
print(s.iloc[2])

30


11.  Slice first 4 elements.

In [ ]:
print(s[0:4])

a    10
b    20
c    30
d    40
dtype: int64


12. Filter values greater than 50.

In [ ]:
print(s[s>50])

f    60
g    70
dtype: int64


13. Replace value 20 with 200.

In [ ]:
s[s==20] = 200
print(s)

a     10
b    200
c     30
d     40
e     50
f     60
g     70
dtype: int64


14. Rename index "a" to "alpha".

In [ ]:
s.rename(index={'a': 'alpha'}, inplace=True)
print(s)

alpha     10
b        200
c         30
d         40
e         50
f         60
g         70
dtype: int64


15. Sort a Series by values.

In [ ]:
print(s.sort_values())

alpha     10
c         30
d         40
e         50
f         60
g         70
b        200
dtype: int64


16. Add 10 to every element in Series.

In [ ]:
print(s+10)

alpha     20
b        210
c         40
d         50
e         60
f         70
g         80
dtype: int64


17. Multiply two Series together.

In [ ]:
s1 = pd.Series([10,20,30,40,50,60,70], index = ['a','b','c','d','e','f','g'])
s2 = pd.Series([10,20,30,40,50,60,70], index = ['x','b','c','d','e','f','g'])
# print(s1*s2)
print(s1.mul(s2, fill_value = 1))

a      10.0
b     400.0
c     900.0
d    1600.0
e    2500.0
f    3600.0
g    4900.0
x      10.0
dtype: float64


18. Find sum of Series.

In [ ]:
print(s1.sum())

280


19. Find mean of values.

In [ ]:
print(s1.mean())

40.0


20. Find median.

In [ ]:
print(s1.median())

40.0


21. Find standard deviation.

In [ ]:
print(s1.std())

21.602468994692867


22. Count non-null values.

In [ ]:
# a = pd.Series(np.random.randint(1,16,15),index = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o'])
a = pd.Series([9,None,5,2,2,None,9,None,9,6], index = ['a','b','c','d','e','f','g','h','i','j'])
print(a)
print(a.notnull().sum())

a    9.0
b    NaN
c    5.0
d    2.0
e    2.0
f    NaN
g    9.0
h    NaN
i    9.0
j    6.0
dtype: float64
7


23. Replace missing values with 0.

In [ ]:
b = a.fillna(0)
print(b)

a    9.0
b    0.0
c    5.0
d    2.0
e    2.0
f    0.0
g    9.0
h    0.0
i    9.0
j    6.0
dtype: float64


24. Drop missing values.

In [ ]:
c = a.dropna()
print(c)

a    9.0
c    5.0
d    2.0
e    2.0
g    9.0
i    9.0
j    6.0
dtype: float64


25. Get top 3 largest values.

In [ ]:
print(c.sort_values(ascending =False).head(3))

a    9.0
i    9.0
g    9.0
dtype: float64


26. Get 2 smallest values.


In [ ]:
print(c.sort_values().head(2))


e    2.0
d    2.0
dtype: float64


27. Apply lambda to square each value.

In [ ]:
print(c.apply(lambda x : x*x))

a    81.0
c    25.0
d     4.0
e     4.0
g    81.0
i    81.0
j    36.0
dtype: float64


28. Count frequency of unique values.


In [ ]:
print(c)
print()
print(c.value_counts())

a    9.0
c    5.0
d    2.0
e    2.0
g    9.0
i    9.0
j    6.0
dtype: float64

9.0    3
2.0    2
5.0    1
6.0    1
Name: count, dtype: int64


29. Reindex Series to include new label "z".

In [ ]:
c = a.dropna()
print(c.index)
print()
c = c.reindex(c.index.append(pd.Index(['z'])),fill_value=6)
print(c)

Index(['a', 'c', 'd', 'e', 'g', 'i', 'j'], dtype='object')

a    9.0
c    5.0
d    2.0
e    2.0
g    9.0
i    9.0
j    6.0
z    6.0
dtype: float64


30. Calculate cumulative sum of Series.

In [ ]:
print(c.cumsum())

a     9.0
c    14.0
d    16.0
e    18.0
g    27.0
i    36.0
j    42.0
z    48.0
dtype: float64


## Dataframe Task

### Manual Data input

Setup for all tasks:
```python

import pandas as pd
import numpy as np
# Use this initial dictionary for tasks where 'data' is needed unless specified otherwise
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "Age": [25, 30, 35, 40, 22, 28, 45],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio"],
    "Salary": [70000, 80000, 120000, 90000, 60000, 75000, 110000]
}
df = pd.DataFrame(data)
```

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace"],
    "Age": [25, 30, 35, 40, 22, 28, 45],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio"],
    "Salary": [70000, 80000, 120000, 90000, 60000, 75000, 110000]
}
df = pd.DataFrame(data)

1. Create and Inspect:

Create a DataFrame from the data dictionary. Print the specific shape of the DataFrame (rows, columns) and show the data types of all columns.

In [ ]:
print(df)
print()
print(df.shape)
print()
print(df.dtypes)

      Name  Age          City  Salary
0    Alice   25      New York   70000
1      Bob   30   Los Angeles   80000
2  Charlie   35       Chicago  120000
3    David   40       Houston   90000
4      Eva   22       Phoenix   60000
5    Frank   28  Philadelphia   75000
6    Grace   45   San Antonio  110000

(7, 4)

Name      object
Age        int64
City      object
Salary     int64
dtype: object


2. Custom Index creation:

Create a new DataFrame df_custom from data but set the index to be specific IDs:

`['ID1', 'ID2', 'ID3', 'ID4', 'ID5', 'ID6', 'ID7'].`


In [ ]:
dfCustom = pd.DataFrame(data, index = ['ID1','ID2','ID3','ID4','ID5','ID6','ID7'])
print(dfCustom)

        Name  Age          City  Salary
ID1    Alice   25      New York   70000
ID2      Bob   30   Los Angeles   80000
ID3  Charlie   35       Chicago  120000
ID4    David   40       Houston   90000
ID5      Eva   22       Phoenix   60000
ID6    Frank   28  Philadelphia   75000
ID7    Grace   45   San Antonio  110000


3. Column Selection:

Create a new DataFrame df_subset containing only the "Name" and "Salary" columns from df.

In [ ]:
dfSubset = df[['Name', 'Salary']]
print(dfSubset)

      Name  Salary
0    Alice   70000
1      Bob   80000
2  Charlie  120000
3    David   90000
4      Eva   60000
5    Frank   75000
6    Grace  110000


4. Row Slicing (Integer):

Use iloc to select rows 2 through 5 `(inclusive of index 2, exclusive of 5 depending on slice logic, or just indices 2,3,4)` and all columns.

In [ ]:
print(dfCustom.iloc[2:5])
print()
print(dfCustom.iloc[2:5,[0,2,3]])

        Name  Age     City  Salary
ID3  Charlie   35  Chicago  120000
ID4    David   40  Houston   90000
ID5      Eva   22  Phoenix   60000

        Name     City  Salary
ID3  Charlie  Chicago  120000
ID4    David  Houston   90000
ID5      Eva  Phoenix   60000


5. Row and Column Slicing (Label):

Use loc to select the "Name" and "Age" for the rows with index labels 1, 3, and 5.

In [ ]:
print(df.loc[[1,3,5],['Name',"Age"]])

    Name  Age
1    Bob   30
3  David   40
5  Frank   28


6. Row and Column Slicing (Label):

Cell Access:

Use iloc to print the "City" of the 4th row (index 3)

In [ ]:
print(df.iloc[[3],[2]])

      City
3  Houston


7. Head and Tail:

Print the first 3 rows and the last 2 rows of the DataFrame in a single script execution.

In [ ]:
print(df.head(3))
print()
print(df.tail(2))

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago  120000

    Name  Age          City  Salary
5  Frank   28  Philadelphia   75000
6  Grace   45   San Antonio  110000


8. Describe Objects:

Use df.describe() but try to include all columns (including objects like strings), not just numbers. (Hint: look up include='all' or check dtypes).

In [ ]:
print(df.describe())
print()
print(df.describe(include='all'))

             Age         Salary
count   7.000000       7.000000
mean   32.142857   86428.571429
std     8.275034   21739.803302
min    22.000000   60000.000000
25%    26.500000   72500.000000
50%    30.000000   80000.000000
75%    37.500000  100000.000000
max    45.000000  120000.000000

         Name        Age      City         Salary
count       7   7.000000         7       7.000000
unique      7        NaN         7            NaN
top     Alice        NaN  New York            NaN
freq        1        NaN         1            NaN
mean      NaN  32.142857       NaN   86428.571429
std       NaN   8.275034       NaN   21739.803302
min       NaN  22.000000       NaN   60000.000000
25%       NaN  26.500000       NaN   72500.000000
50%       NaN  30.000000       NaN   80000.000000
75%       NaN  37.500000       NaN  100000.000000
max       NaN  45.000000       NaN  120000.000000


9. Rename Single:

Rename the "Salary" column to "Annual Income" in place (or reassign to df).

In [ ]:
df.rename(columns={"Salary":"Annual Income"}, inplace=True)
print(df)

      Name  Age          City  Annual Income
0    Alice   25      New York          70000
1      Bob   30   Los Angeles          80000
2  Charlie   35       Chicago         120000
3    David   40       Houston          90000
4      Eva   22       Phoenix          60000
5    Frank   28  Philadelphia          75000
6    Grace   45   San Antonio         110000


10. Rename Multiple:

Rename "Name" to "Full Name" and "City" to "Location" simultaneously.


In [ ]:
df.rename(columns={"Name":"Full Name", "City":"Location"}, inplace=True)
print(df)

  Full Name  Age      Location  Annual Income
0     Alice   25      New York          70000
1       Bob   30   Los Angeles          80000
2   Charlie   35       Chicago         120000
3     David   40       Houston          90000
4       Eva   22       Phoenix          60000
5     Frank   28  Philadelphia          75000
6     Grace   45   San Antonio         110000


11. Drop Column:

Remove the "City" column from the DataFrame.


In [ ]:
print(df)

  Full Name  Age      Location  Annual Income
0     Alice   25      New York          70000
1       Bob   30   Los Angeles          80000
2   Charlie   35       Chicago         120000
3     David   40       Houston          90000
4       Eva   22       Phoenix          60000
5     Frank   28  Philadelphia          75000
6     Grace   45   San Antonio         110000


In [ ]:
df.drop(columns="Location", inplace =True)
print(df)

  Full Name  Age  Annual Income
0     Alice   25          70000
1       Bob   30          80000
2   Charlie   35         120000
3     David   40          90000
4       Eva   22          60000
5     Frank   28          75000
6     Grace   45         110000


12. Drop Row:

Remove the row at index 3.

In [ ]:
df.drop(index=3, inplace=True)
print(df)

  Full Name  Age  Annual Income
0     Alice   25          70000
1       Bob   30          80000
2   Charlie   35         120000
4       Eva   22          60000
5     Frank   28          75000
6     Grace   45         110000


13. Add Constant Column:

Add a new column "Country" and populate it with "USA" for all rows.


In [ ]:
df.insert(1, "Country", "USA")
print(df)

  Full Name Country  Age  Annual Income
0     Alice     USA   25          70000
1       Bob     USA   30          80000
2   Charlie     USA   35         120000
4       Eva     USA   22          60000
5     Frank     USA   28          75000
6     Grace     USA   45         110000


14. Add Calculated Column (Born Year):

Assuming the current year is 2025, create a new column "Birth Year" by subtracting "Age" from 2025.

In [ ]:
currYear = 2025
df.insert(3, "Birth Year", currYear-df["Age"])
print(df)

  Full Name Country  Age  Birth Year  Annual Income
0     Alice     USA   25        2000          70000
1       Bob     USA   30        1995          80000
2   Charlie     USA   35        1990         120000
4       Eva     USA   22        2003          60000
5     Frank     USA   28        1997          75000
6     Grace     USA   45        1980         110000


15. Add List Column:

Add a new column "Department" using this list: ['HR', 'Eng', 'Eng', 'Sales', 'HR', 'Sales', 'Admin'].


In [ ]:
df.insert(5, "Department", ["HR", "Eng","Eng","HR","Sales","Admin"])
print(df)

  Full Name Country  Age  Birth Year  Annual Income Department
0     Alice     USA   25        2000          70000         HR
1       Bob     USA   30        1995          80000        Eng
2   Charlie     USA   35        1990         120000        Eng
4       Eva     USA   22        2003          60000         HR
5     Frank     USA   28        1997          75000      Sales
6     Grace     USA   45        1980         110000      Admin


16. Numpy conversion:

 Convert the underlying data of the DataFrame to a NumPy array and print it.


In [ ]:
a = np.array(df)
print(a)

[['Alice' 'USA' 25 2000 70000 'HR']
 ['Bob' 'USA' 30 1995 80000 'Eng']
 ['Charlie' 'USA' 35 1990 120000 'Eng']
 ['Eva' 'USA' 22 2003 60000 'HR']
 ['Frank' 'USA' 28 1997 75000 'Sales']
 ['Grace' 'USA' 45 1980 110000 'Admin']]


17. Empty DataFrame:

Create an empty DataFrame. Then add two columns "A" and "B" with 3 values each.


In [ ]:
emptyDf = pd.DataFrame()
print(emptyDf)
# a = np.arange(1,7).reshape(3,2)
emptyDf.insert(0, "A", [1,2,3])
emptyDf.insert(1, "B", [4,5,6])

print(emptyDf)

Empty DataFrame
Columns: []
Index: []
   A  B
0  1  4
1  2  5
2  3  6


18. Reorder Columns:

Rearrange the columns so that "Age" appears before "Name".


In [ ]:
print(df)

  Full Name Country  Age  Birth Year  Annual Income Department
0     Alice     USA   25        2000          70000         HR
1       Bob     USA   30        1995          80000        Eng
2   Charlie     USA   35        1990         120000        Eng
4       Eva     USA   22        2003          60000         HR
5     Frank     USA   28        1997          75000      Sales
6     Grace     USA   45        1980         110000      Admin


In [ ]:
age = df.pop("Age")
df.insert(0, "Age", age)
print(df)

   Age Full Name Country  Birth Year  Annual Income Department
0   25     Alice     USA        2000          70000         HR
1   30       Bob     USA        1995          80000        Eng
2   35   Charlie     USA        1990         120000        Eng
4   22       Eva     USA        2003          60000         HR
5   28     Frank     USA        1997          75000      Sales
6   45     Grace     USA        1980         110000      Admin


19. Conditional Update (Manual):

Update the "Age" of "Alice" (index 0) to 26 using at or loc.


In [ ]:
df.loc[0,"Age"] = 26
print(df)

   Age Full Name Country  Birth Year  Annual Income Department
0   26     Alice     USA        2000          70000         HR
1   30       Bob     USA        1995          80000        Eng
2   35   Charlie     USA        1990         120000        Eng
4   22       Eva     USA        2003          60000         HR
5   28     Frank     USA        1997          75000      Sales
6   45     Grace     USA        1980         110000      Admin


20. Random Sample:

Specificy a random seed (optional) and select a random sample of 3 rows from the DataFrame.

In [ ]:
rd.seed(10)
print(df.sample(3))

   Age Full Name Country  Birth Year  Annual Income Department
4   22       Eva     USA        2003          60000         HR
1   30       Bob     USA        1995          80000        Eng
0   26     Alice     USA        2000          70000         HR


###.read_csv()

Dataset link: https://drive.google.com/file/d/1vqmvfEcyRgy_9zUlnjYJ5W3GoKzhTDbu/view?usp=drive_link

1. Load Movieratingdata1.csv and show all rows & columns.

In [ ]:
df = pd.read_csv("Movieratingdata1.csv")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(df)

    USER_ID   MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0    4642044          Riot             2015   
1       NaN        NaN            NaN             NaN   
2       3.0  not value            NaN            2014   
3       4.0    1390411            NaN            2015   
4       5.0    6306064            NaN   not available   
5       6.0    6306064            NaN     not mension   
6       7.0    2719848            NaN            2015   
7       8.0     462504            NaN            2006   
8       9.0        NaN            NaN            2020   
9      10.0     163225  The Revenant             2015   
10     11.0    1663202            NaN            2015   
11     12.0    1663202  The Revenant             2021   

                                               GENRES         RATING  
0                                              Action            NaN  
1                                                 NaN            NaN  
2                                            

2. Custom Missing Values:

While loading, treat
"not available" and "not mension" as NaN in PRODUCTION_YEAR.

In [ ]:
df = pd.read_csv("Movieratingdata1.csv", na_values=["not available","not mension", "not value"])
print(df)

    USER_ID   MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR  \
0       1.0  4642044.0          Riot            2015.0   
1       NaN        NaN            NaN              NaN   
2       3.0        NaN            NaN           2014.0   
3       4.0  1390411.0            NaN           2015.0   
4       5.0  6306064.0            NaN              NaN   
5       6.0  6306064.0            NaN              NaN   
6       7.0  2719848.0            NaN           2015.0   
7       8.0   462504.0            NaN           2006.0   
8       9.0        NaN            NaN           2020.0   
9      10.0   163225.0  The Revenant            2015.0   
10     11.0  1663202.0            NaN           2015.0   
11     12.0  1663202.0  The Revenant            2021.0   

                                               GENRES  RATING  
0                                              Action     NaN  
1                                                 NaN     NaN  
2                                                 NaN

3. Replace Text Missing Values

Replace "not available", "not mension", "not value" in whole dataframe with np.nan.


In [ ]:
df = pd.read_csv("Movieratingdata1.csv")
df.replace(["not available", "not mension", "not value"], np.nan, inplace = True)
print(df)

    USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0  4642044          Riot             2015   
1       NaN      NaN            NaN             NaN   
2       3.0      NaN            NaN            2014   
3       4.0  1390411            NaN            2015   
4       5.0  6306064            NaN             NaN   
5       6.0  6306064            NaN             NaN   
6       7.0  2719848            NaN            2015   
7       8.0   462504            NaN            2006   
8       9.0      NaN            NaN            2020   
9      10.0   163225  The Revenant             2015   
10     11.0  1663202            NaN            2015   
11     12.0  1663202  The Revenant             2021   

                                               GENRES RATING  
0                                              Action    NaN  
1                                                 NaN    NaN  
2                                                 NaN    NaN  
3                               

4. Count Total Missing Values

Find total number of missing values in the dataset.

In [ ]:
print(df.isnull().sum().sum())

24


5. Column-wise Missing Count

Show missing values count for each column.

In [ ]:
print(df.isnull().sum())

USER_ID            1
MOVIE_ID           3
MOVIE_TITLE        9
PRODUCTION_YEAR    3
GENRES             3
RATING             5
dtype: int64


6. Drop Rows Where All Values Missing

Remove rows where every column is NaN.

In [ ]:
df1 = df.dropna(how = "all")
print(f'DF1\n\n{df1}')

DF1

    USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0  4642044          Riot             2015   
2       3.0      NaN            NaN            2014   
3       4.0  1390411            NaN            2015   
4       5.0  6306064            NaN             NaN   
5       6.0  6306064            NaN             NaN   
6       7.0  2719848            NaN            2015   
7       8.0   462504            NaN            2006   
8       9.0      NaN            NaN            2020   
9      10.0   163225  The Revenant             2015   
10     11.0  1663202            NaN            2015   
11     12.0  1663202  The Revenant             2021   

                                               GENRES RATING  
0                                              Action    NaN  
2                                                 NaN    NaN  
3                                                 NaN      5  
4   Action|Adventure|Biography|Drama|Romance|Thriller      4  
5   Action|Adventur

7. Drop Columns with Any Missing Value

Remove columns that contain at least one NaN.

In [ ]:
df2 = df.dropna(axis = 1)
print(f'DF2\n\n{df2}')

DF2

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


8. Fill Missing Movie ID

Fill missing MOVIE_ID with 0.

In [ ]:
# print(df)
# df['MOVIE_ID'].fillna(0, inplace = True)
df.fillna({"MOVIE_ID":0}, inplace = True)
print(df)

    USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0  4642044          Riot             2015   
1       NaN        0            NaN             NaN   
2       3.0        0            NaN            2014   
3       4.0  1390411            NaN            2015   
4       5.0  6306064            NaN             NaN   
5       6.0  6306064            NaN             NaN   
6       7.0  2719848            NaN            2015   
7       8.0   462504            NaN            2006   
8       9.0        0            NaN            2020   
9      10.0   163225  The Revenant             2015   
10     11.0  1663202            NaN            2015   
11     12.0  1663202  The Revenant             2021   

                                               GENRES RATING  
0                                              Action    NaN  
1                                                 NaN    NaN  
2                                                 NaN    NaN  
3                               

9. Fill Missing Production Year

Replace missing PRODUCTION_YEAR with 2000.

In [ ]:
# df['PRODUCTION_YEAR'].fillna(2000,inplace = True)
df.fillna({"PRODUCTION_YEAR": 2000}, inplace =True)
print(df)

    USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0  4642044          Riot             2015   
1       NaN        0            NaN            2000   
2       3.0        0            NaN            2014   
3       4.0  1390411            NaN            2015   
4       5.0  6306064            NaN            2000   
5       6.0  6306064            NaN            2000   
6       7.0  2719848            NaN            2015   
7       8.0   462504            NaN            2006   
8       9.0        0            NaN            2020   
9      10.0   163225  The Revenant             2015   
10     11.0  1663202            NaN            2015   
11     12.0  1663202  The Revenant             2021   

                                               GENRES RATING  
0                                              Action    NaN  
1                                                 NaN    NaN  
2                                                 NaN    NaN  
3                               

10. Fill Missing Ratings with Mean

Convert RATING to float and fill missing values using average rating.

In [ ]:
df['RATING']=df["RATING"].astype(float)
# df.fillna({"RATING": df["RATING"].mean()}, inplace =True)  # can't do
df['RATING'] = df['RATING'].fillna(df['RATING'].mean())
print(df)

    USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0  4642044          Riot             2015   
1       NaN        0            NaN            2000   
2       3.0        0            NaN            2014   
3       4.0  1390411            NaN            2015   
4       5.0  6306064            NaN            2000   
5       6.0  6306064            NaN            2000   
6       7.0  2719848            NaN            2015   
7       8.0   462504            NaN            2006   
8       9.0        0            NaN            2020   
9      10.0   163225  The Revenant             2015   
10     11.0  1663202            NaN            2015   
11     12.0  1663202  The Revenant             2021   

                                               GENRES     RATING  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                                                 NaN   6.857143  
3               

11. Replace Wrong Entry

Replace "1390411" with "The Batman".

In [ ]:
df.replace('1390411', "The Batman", inplace = True)
print(df)

    USER_ID    MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR  \
0       1.0     4642044          Riot             2015   
1       NaN           0            NaN            2000   
2       3.0           0            NaN            2014   
3       4.0  The Batman            NaN            2015   
4       5.0     6306064            NaN            2000   
5       6.0     6306064            NaN            2000   
6       7.0     2719848            NaN            2015   
7       8.0      462504            NaN            2006   
8       9.0           0            NaN            2020   
9      10.0      163225  The Revenant             2015   
10     11.0     1663202            NaN            2015   
11     12.0     1663202  The Revenant             2021   

                                               GENRES     RATING  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                                           

12. Rename Columns

Rename columns to lowercase.

In [ ]:
df.rename(columns = str.lower, inplace = True)
print(df)

    user_id    movie_id    movie_title production_year  \
0       1.0     4642044          Riot             2015   
1       NaN           0            NaN            2000   
2       3.0           0            NaN            2014   
3       4.0  The Batman            NaN            2015   
4       5.0     6306064            NaN            2000   
5       6.0     6306064            NaN            2000   
6       7.0     2719848            NaN            2015   
7       8.0      462504            NaN            2006   
8       9.0           0            NaN            2020   
9      10.0      163225  The Revenant             2015   
10     11.0     1663202            NaN            2015   
11     12.0     1663202  The Revenant             2021   

                                               genres     rating  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                                           

13. Change Data Type

Convert PRODUCTION_YEAR to integer.

In [ ]:
df['production_year'] = df['production_year'].astype(int)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   user_id          11 non-null     float64
 1   movie_id         12 non-null     object 
 2   movie_title      3 non-null      object 
 3   production_year  12 non-null     int64  
 4   genres           9 non-null      object 
 5   rating           12 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 708.0+ bytes
None


14.  Remove Duplicate Rows

Delete duplicate rows from dataset.

In [ ]:
df.drop_duplicates(inplace = True)
print(df)

    user_id    movie_id    movie_title  production_year  \
0       1.0     4642044          Riot              2015   
1       NaN           0            NaN             2000   
2       3.0           0            NaN             2014   
3       4.0  The Batman            NaN             2015   
4       5.0     6306064            NaN             2000   
5       6.0     6306064            NaN             2000   
6       7.0     2719848            NaN             2015   
7       8.0      462504            NaN             2006   
8       9.0           0            NaN             2020   
9      10.0      163225  The Revenant              2015   
10     11.0     1663202            NaN             2015   
11     12.0     1663202  The Revenant              2021   

                                               genres     rating  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                              

15. Show Data Types

Display datatype of each column.

In [ ]:
print(df.dtypes)

user_id            float64
movie_id            object
movie_title         object
production_year      int64
genres              object
rating             float64
dtype: object


16. Reset Index

Reset the dataframe index after cleaning.

In [ ]:
df.reset_index(drop = True)
print(df)

    user_id    movie_id    movie_title  production_year  \
0       1.0     4642044          Riot              2015   
1       NaN           0            NaN             2000   
2       3.0           0            NaN             2014   
3       4.0  The Batman            NaN             2015   
4       5.0     6306064            NaN             2000   
5       6.0     6306064            NaN             2000   
6       7.0     2719848            NaN             2015   
7       8.0      462504            NaN             2006   
8       9.0           0            NaN             2020   
9      10.0      163225  The Revenant              2015   
10     11.0     1663202            NaN             2015   
11     12.0     1663202  The Revenant              2021   

                                               genres     rating  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                              

17. Drop Movie Title Column

Remove MOVIE_TITLE column.

In [ ]:
df.drop(columns = "movie_title", inplace = True)
print(df)

    user_id    movie_id  production_year  \
0       1.0     4642044             2015   
1       NaN           0             2000   
2       3.0           0             2014   
3       4.0  The Batman             2015   
4       5.0     6306064             2000   
5       6.0     6306064             2000   
6       7.0     2719848             2015   
7       8.0      462504             2006   
8       9.0           0             2020   
9      10.0      163225             2015   
10     11.0     1663202             2015   
11     12.0     1663202             2021   

                                               genres     rating  
0                                              Action   6.857143  
1                                                 NaN   6.857143  
2                                                 NaN   6.857143  
3                                                 NaN   5.000000  
4   Action|Adventure|Biography|Drama|Romance|Thriller   4.000000  
5   Action|Adventure|Biog

18. Fill All Remaining NaNs

Fill all remaining NaN values with "Unknown".

In [ ]:
df.fillna("Unknown", inplace = True)
print(df)
#

    user_id    movie_id  production_year  \
0       1.0     4642044             2015   
1   Unknown           0             2000   
2       3.0           0             2014   
3       4.0  The Batman             2015   
4       5.0     6306064             2000   
5       6.0     6306064             2000   
6       7.0     2719848             2015   
7       8.0      462504             2006   
8       9.0           0             2020   
9      10.0      163225             2015   
10     11.0     1663202             2015   
11     12.0     1663202             2021   

                                               genres     rating  
0                                              Action   6.857143  
1                                             Unknown   6.857143  
2                                             Unknown   6.857143  
3                                             Unknown   5.000000  
4   Action|Adventure|Biography|Drama|Romance|Thriller   4.000000  
5   Action|Adventure|Biog

/tmp/ipython-input-588485348.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Unknown", inplace = True)


19. Describe Dataset

Show summary statistics of numeric columns.

In [ ]:
print(df.describe())

       production_year     rating
count        12.000000  12.000000
mean       2011.333333   6.857143
std           7.726381   1.780121
min        2000.000000   4.000000
25%        2004.500000   5.750000
50%        2015.000000   6.857143
75%        2015.000000   7.392857
max        2021.000000  10.000000
